name: ip_manager_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  shared_preferences: ^2.2.3
  provider: ^6.0.5
  cupertino_icons: ^1.0.8

  # ğŸ‘‡ cÃ¡c package scan/ping máº¡ng LAN
  network_info_plus: ^5.0.3
  network_tools: ^5.0.3   # thay cho ping_discover_network (package cÅ© Ä‘Ã£ bá»)

  # ğŸ‘‡ náº¿u báº¡n cáº§n xuáº¥t CSV/Excel
  csv: ^6.0.0
  excel: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
